aerospike:
  build: ./aerospike
  ports:
    - 3000:3000
    - 3001:3001
    - 3002:3002
    - 3003:3003 
  volumes:
  - ./volumes/aerospike/data:/opt/aerospike/data

server:
  build: ./server
  ports:
    - 80:3333
  volumes:
    - ./server/application/src:/application/src
